import { useState } from 'react';

import clsx from 'clsx';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { FiEye } from 'react-icons/fi';

import { getHeaderLayout } from '@/components';
import { BaseModal, Button, Checkbox, Input, SearchInput, Textarea } from '@/shared/ui';
import { getStaticPropsWithLocale } from '@/shared/utils';
import { useGetMeQuery } from '@/store/api';
import cls from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

const Home: InferGetStaticPropsType<typeof getStaticProps> = () => {
  const [open, setOpen] = useState(false);
  const [checkbox, setCheckbox] = useState(false);

  const { data } = useGetMeQuery();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <main className={clsx(cls.main, inter.className)}>
        <Input placeholder="Email" label="Email" type="password" />

        <Button>Button</Button>

        <Button variant="outlined">Button</Button>

        <Button variant="subtle">Button</Button>

        <Button variant="default">Button</Button>

        <Button leftIcon={<FiEye />}>wefwef</Button>

        <SearchInput />
        <SearchInput fullWidth />

        <Textarea errorMessage="error" />

        <Button onClick={() => setOpen(!open)}>Show modal</Button>
        <BaseModal
          title="We have sent a link to confirm your email to epam@epam.com"
          isOpen={open}
          closeCallback={() => {
            console.log('Close callback');
            setOpen(!open);
          }}
        >
          <p>We have sent a link to confirm your </p>
        </BaseModal>

        <Checkbox
          checked={checkbox}
          onChange={e => setCheckbox(e.target.checked)}
          label="Some field"
        />
      </main>
    </>
  );
};

Home.getLayout = getHeaderLayout;
export default Home;

export const getStaticProps: GetStaticProps = getStaticPropsWithLocale();
